/**
 * `nx health [--factory|--lifeops]` — terminal dashboard.
 *
 * Reads:
 *   - registry-factory.yaml / registry-lifeops.yaml (per ADR-0003)
 *   - registry-external-mcp.yaml (per ADR-0005)
 *   - scorecard.json (generated by verify-all)
 *
 * Ink renders a compact summary.
 */

import { existsSync, readFileSync } from "node:fs";
import { render } from "ink";
import * as React from "react";
void React; // JSX runtime imports React implicitly under verbatimModuleSyntax
import type { NexuralConfig } from "../config.js";
import { HealthDashboard, type HealthData } from "../ui/HealthDashboard.js";

export async function runHealth(_config: NexuralConfig): Promise<void> {
  const data = collectHealth();
  const { waitUntilExit } = render(<HealthDashboard data={data} />);
  await waitUntilExit();
}

function collectHealth(): HealthData {
  return {
    federations: (["factory", "lifeops"] as const).map((f) => {
      const path = `registry-${f}.yaml`;
      if (!existsSync(path)) return { name: f, count: 0, registry_path: path, present: false };
      const content = readFileSync(path, "utf8");
      const count = (content.match(/^\s+- name:/gm) ?? []).length;
      return { name: f, count, registry_path: path, present: true };
    }),
    scorecard: readScorecard(),
    decay: { stale: 0, quarantined: 0 }, // Phase 4 wires decay from telemetry + scorecard
    externalMcps: readExternalMcps(),
  };
}

function readScorecard(): HealthData["scorecard"] {
  if (!existsSync("scorecard.json")) return { present: false };
  try {
    const sc = JSON.parse(readFileSync("scorecard.json", "utf8"));
    return {
      present: true,
      meanScore: sc.aggregate?.mean_score ?? 0,
      below80: sc.aggregate?.below_80_count ?? 0,
    };
  } catch {
    return { present: false };
  }
}

function readExternalMcps(): HealthData["externalMcps"] {
  if (!existsSync("registry-external-mcp.yaml")) return [];
  const content = readFileSync("registry-external-mcp.yaml", "utf8");
  const names = [...content.matchAll(/- name:\s*(\S+)/g)].map((m) => m[1]!);
  const scores = [...content.matchAll(/score:\s*(\d+)/g)].map((m) => parseInt(m[1]!, 10));
  return names.map((name, i) => ({ name, score: scores[i] ?? 0 }));
}
