import { readScorecard } from "@/lib/data";

export const dynamic = "force-dynamic";

export default function Scorecard() {
  const sc = readScorecard();
  return (
    <section>
      <h1>Scorecard</h1>
      <p style={{ color: "#a3a3a3" }}>
        Generated by <code>nexural-qa-os</code> via <code>scripts/verify-all.mjs</code>. Per
        ARCHITECTURE §10.
      </p>
      {!sc.present ? (
        <p style={{ color: "#737373" }}>
          <code>scorecard.json</code> not present. Run <code>pnpm verify-all</code>.
        </p>
      ) : (
        <>
          {sc.aggregate && (
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(4, 1fr)",
                gap: "1rem",
                marginBottom: "2rem",
              }}
            >
              <Stat label="Mean" value={sc.aggregate.mean_score} />
              <Stat label="Median" value={sc.aggregate.median_score} />
              <Stat label="Below 80" value={sc.aggregate.below_80_count} tone="warn" />
              <Stat label="Below 90" value={sc.aggregate.below_90_count} />
            </div>
          )}
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ borderBottom: "1px solid #262626", textAlign: "left" }}>
                <th style={{ padding: "0.5rem" }}>Warehouse</th>
                <th style={{ padding: "0.5rem" }}>Federation</th>
                <th style={{ padding: "0.5rem" }}>Score</th>
                <th style={{ padding: "0.5rem" }}>Grade</th>
              </tr>
            </thead>
            <tbody>
              {sc.warehouses.map((w) => (
                <tr key={w.name} style={{ borderBottom: "1px solid #1a1a1a" }}>
                  <td style={{ padding: "0.5rem" }}>{w.name}</td>
                  <td style={{ padding: "0.5rem" }}>{w.federation}</td>
                  <td style={{ padding: "0.5rem" }}>{w.score}</td>
                  <td style={{ padding: "0.5rem" }}>{w.grade}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}
    </section>
  );
}

function Stat({
  label,
  value,
  tone = "ok",
}: {
  readonly label: string;
  readonly value: number;
  readonly tone?: "ok" | "warn";
}) {
  return (
    <div
      style={{
        background: "#171717",
        border: "1px solid #262626",
        borderRadius: 8,
        padding: "1rem",
      }}
    >
      <div style={{ fontSize: "0.8rem", color: "#a3a3a3" }}>{label}</div>
      <div
        style={{
          fontSize: "1.5rem",
          fontWeight: 600,
          color: tone === "warn" && value > 0 ? "#f59e0b" : "#e5e5e5",
        }}
      >
        {value}
      </div>
    </div>
  );
}
