#!/usr/bin/env node
/**
 * Weekly ecosystem digest. Per ADR-0013 + Tier-2 daily-ops.
 *
 * Walks the 4 ecosystem repos via the GitHub API, aggregates the last 7 days
 * of commits + releases, and writes a digest markdown file the cron commits
 * back to evidence/ecosystem/.
 *
 * Surfaces what changed across the ecosystem without you having to check
 * each repo individually.
 *
 * Runs locally (uses GH_TOKEN or the gh CLI if present) and in GitHub
 * Actions (Friday morning cron). See .github/workflows/ecosystem-digest.yml.
 */

import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPOS = [
  { owner: "JasonTeixeira", repo: "nexural-meta", role: "control plane" },
  { owner: "JasonTeixeira", repo: "ai-warehouse", role: "parts catalog" },
  { owner: "JasonTeixeira", repo: "nexural-qa-os", role: "QA verification" },
  { owner: "JasonTeixeira", repo: "voice-engine", role: "voice toolkit" },
];

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SINCE_DAYS = 7;

function ghApi(endpoint) {
  // Use gh CLI if available (handles auth automatically)
  try {
    return execSync(`gh api ${endpoint}`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (err) {
    return null;
  }
}

function fetchCommits(owner, repo, since) {
  const raw = ghApi(`repos/${owner}/${repo}/commits?since=${since}&per_page=30`);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    // GH 404 returns `{ message: "Not Found" }` instead of an array
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function fetchReleases(owner, repo) {
  const raw = ghApi(`repos/${owner}/${repo}/releases?per_page=10`);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function summarize(commit) {
  const msg = commit.commit?.message ?? "";
  const firstLine = msg.split("\n")[0]?.slice(0, 100) ?? "(no message)";
  const sha = commit.sha?.slice(0, 7) ?? "???????";
  const date = (commit.commit?.author?.date ?? "").slice(0, 10);
  return `- \`${sha}\` ${date} — ${firstLine}`;
}

async function main() {
  const sinceMs = Date.now() - SINCE_DAYS * 24 * 60 * 60 * 1000;
  const sinceIso = new Date(sinceMs).toISOString();
  const dateLabel = new Date().toISOString().slice(0, 10);

  const lines = [];
  lines.push(`# Ecosystem digest — ${dateLabel}`);
  lines.push("");
  lines.push(
    `Last ${SINCE_DAYS} days of activity across the 4-repo Sage Ideas ecosystem. Generated by \`scripts/ecosystem-digest.mjs\`.`,
  );
  lines.push("");
  lines.push(`Window: \`${sinceIso}\` → \`${new Date().toISOString()}\``);
  lines.push("");

  let totalCommits = 0;
  let totalReleases = 0;
  const inactiveRepos = [];

  for (const r of REPOS) {
    lines.push(`---`);
    lines.push("");
    lines.push(`## \`${r.owner}/${r.repo}\` (${r.role})`);
    lines.push("");

    const commits = fetchCommits(r.owner, r.repo, sinceIso);
    if (commits === null) {
      lines.push(`> ⚠ couldn't fetch — repo private/missing or gh auth not available?`);
      lines.push("");
      continue;
    }

    if (commits.length === 0) {
      lines.push(`_No commits in the last ${SINCE_DAYS} days._`);
      lines.push("");
      inactiveRepos.push(r.repo);
    } else {
      lines.push(`**${commits.length} commit${commits.length === 1 ? "" : "s"}:**`);
      lines.push("");
      for (const c of commits.slice(0, 15)) {
        lines.push(summarize(c));
      }
      if (commits.length > 15) lines.push(`- … and ${commits.length - 15} more`);
      lines.push("");
      totalCommits += commits.length;
    }

    const releases = fetchReleases(r.owner, r.repo);
    if (releases && releases.length > 0) {
      const recent = releases.filter((rel) => {
        const t = Date.parse(rel.published_at ?? rel.created_at ?? "");
        return Number.isFinite(t) && t >= sinceMs;
      });
      if (recent.length > 0) {
        lines.push(`**Releases this week:**`);
        lines.push("");
        for (const rel of recent) {
          const tag = rel.tag_name ?? "?";
          const name = rel.name ?? "(no name)";
          const date = (rel.published_at ?? "").slice(0, 10);
          lines.push(`- [\`${tag}\`](${rel.html_url}) ${date} — ${name}`);
        }
        lines.push("");
        totalReleases += recent.length;
      }
    }
  }

  lines.push(`---`);
  lines.push("");
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`- Total commits across ecosystem: **${totalCommits}**`);
  lines.push(`- Total releases this week: **${totalReleases}**`);
  if (inactiveRepos.length > 0) {
    lines.push(`- Quiet repos: ${inactiveRepos.map((r) => `\`${r}\``).join(", ")}`);
  }
  lines.push("");
  lines.push(`_Next digest: ${nextFriday().toISOString().slice(0, 10)}_`);

  const md = lines.join("\n") + "\n";

  const outDir = join(ROOT, "evidence", "ecosystem");
  mkdirSync(outDir, { recursive: true });
  const stamp = dateLabel.replace(/-/g, "");
  const outPath = join(outDir, `digest-${stamp}.md`);
  writeFileSync(outPath, md);
  writeFileSync(join(outDir, "latest.md"), md);

  console.error(
    `[ecosystem-digest] ${REPOS.length} repos, ${totalCommits} commits, ${totalReleases} releases`,
  );
  console.error(`[ecosystem-digest] wrote ${outPath}`);
}

function nextFriday() {
  const now = new Date();
  const day = now.getUTCDay(); // 0 = Sunday, 5 = Friday
  const daysUntil = (5 - day + 7) % 7 || 7;
  return new Date(now.getTime() + daysUntil * 24 * 60 * 60 * 1000);
}

main().catch((err) => {
  console.error("[ecosystem-digest] fatal:", err);
  process.exit(1);
});
